# http://www.invalidchecksum.net/2015/08/travis-ci-gce-docker-test-kitchen.html
sudo: required

services:
- docker

before_install:
- curl -s https://packagecloud.io/install/repositories/chef/stable/script.deb.sh | sudo bash

install:
- sudo apt-get install chefdk
- /opt/chefdk/bin/chef gem install kitchen-docker-api

script:
- /opt/chefdk/bin/chef exec rake style
- /opt/chefdk/bin/chef exec rake unit
- /opt/chefdk/bin/chef exec kitchen test $KITCHEN_INSTANCE -d never

env:
  global:
    - KITCHEN_YAML=.kitchen.docker.yml
  matrix:
    - KITCHEN_INSTANCE='default-centos-511'
    - KITCHEN_INSTANCE='default-centos-66'
    - KITCHEN_INSTANCE='default-centos-7'
    - KITCHEN_INSTANCE='plugins-centos-511'
    - KITCHEN_INSTANCE='plugins-centos-66'
    - KITCHEN_INSTANCE='plugins-centos-7'
    - KITCHEN_INSTANCE='users-centos-511'
    - KITCHEN_INSTANCE='users-centos-66'
    - KITCHEN_INSTANCE='users-centos-7'
    - KITCHEN_INSTANCE='enable-epel-centos-511'
    - KITCHEN_INSTANCE='enable-epel-centos-66'
    - KITCHEN_INSTANCE='enable-epel-centos-7'
