# http://www.invalidchecksum.net/2015/08/travis-ci-gce-docker-test-kitchen.html
sudo: required

services:
- docker

before_install:
- curl -s https://packagecloud.io/install/repositories/chef/stable/script.deb.sh | sudo bash
- sudo apt-add-repository 'deb http://download.virtualbox.org/virtualbox/debian trusty contrib'
- wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
- sudo apt-get update

install:
- sudo apt-get install chefdk
- sudo apt-get install linux-headers-generic
- sudo apt-get install dkms
- sudo apt-get install virtualbox-5.0
- wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
- sudo dpkg -i vagrant_1.7.4_x86_64.deb
- /opt/chefdk/bin/chef gem install kitchen-docker-api

script:
- /opt/chefdk/bin/chef exec rake style
- /opt/chefdk/bin/chef exec rake unit
- /opt/chefdk/bin/chef exec rake integration:vagrant
# - /opt/chefdk/bin/chef exec kitchen test $KITCHEN_INSTANCE -d never
#
# env:
#   global:
#     - KITCHEN_YAML=.kitchen.docker.yml
#   matrix:
#     - KITCHEN_INSTANCE='default-centos-5'
#     - KITCHEN_INSTANCE='default-centos-6'
#     - KITCHEN_INSTANCE='default-centos-7'
#     - KITCHEN_INSTANCE='plugins-centos-6'
#     - KITCHEN_INSTANCE='plugins-centos-7'
#     - KITCHEN_INSTANCE='users-centos-5'
#     - KITCHEN_INSTANCE='users-centos-6'
#     - KITCHEN_INSTANCE='users-centos-7'
#     - KITCHEN_INSTANCE='enable-epel-centos-5'
#     - KITCHEN_INSTANCE='enable-epel-centos-6'
#     - KITCHEN_INSTANCE='enable-epel-centos-7'
